version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres_nexi
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_DB=nodo
      - POSTGRES_USER=cfg
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=root
