info:
  application:
    description: '@project.description@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'
    name: '@project.name@'
  properties:
    environment: ${ENV:azure}
cors:
  configuration: '${CORS_CONFIGURATION:''{"origins": ["*"], "methods": ["*"]}''}'
server:
  port: '8080'
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: health,info
    jmx:
      exposure:
        include: health,info
  info:
    env:
      enabled: 'true'
  health:
    readinessState:
      enabled: 'true'
    livenessState:
      enabled: 'true'
  endpoint:
    health:
      probes:
        enabled: 'true'
app:
  trimCacheColumn: 'true'
  identifiers:
    pagopa-postgres: ${DB_PAGOPA_POSTGRES_SERVICE_IDENTIFIER}
    nexi-postgres: ${DB_NEXI_POSTGRES_SERVICE_IDENTIFIER}
    nexi-oracle: ${DB_NEXI_ORACLE_SERVICE_IDENTIFIER}

spring:
  datasource:
    pagopa:
      postgres:
        url: ${DB_PAGOPA_POSTGRES_URL}
        username: ${DB_PAGOPA_POSTGRES_USER}
        password: ${DB_PAGOPA_POSTGRES_PASSWORD}
        ##permette di abilitare/disabilitare il datasource al db Postgres PagoPA
        enabled: ${DB_PAGOPA_POSTGRES_ENABLED:'false'}
    nexi:
      oracle:
        url: ${DB_NEXI_ORACLE_URL}
        username: ${DB_NEXI_ORACLE_USER}
        password: ${DB_NEXI_ORACLE_PASSWORD}
        ##permette di abilitare/disabilitare il datasource al db Oracle Nexi
        enabled: ${DB_NEXI_ORACLE_ENABLED:'false'}
      postgres:
        url: ${DB_NEXI_POSTGRES_URL}
        username: ${DB_NEXI_POSTGRES_USER}
        password: ${DB_NEXI_POSTGRES_PASSWORD}
        ##permette di abilitare/disabilitare il datasource al db Postgres Nexi
        enabled: ${DB_NEXI_POSTGRES_ENABLED:'false'}
  jpa:
    show-sql: 'false'

stand-in-manager:
  rx-connection-string: ${STAND_IN_MANAGER_RX_CONNECTION_STRING}
  rx-name: nodo-dei-pagamenti-stand-in
  service:
    host: ${STAND_IN_MANAGER_URL}
    subscriptionKey: ${STAND_IN_MANAGER_SUBSCRIPTION_KEY}
    ##permette di abilitare/disabilitare la chiamata al servizio tramite API
    enabled: 'true'
  sa-connection-string: ${STAND_IN_MANAGER_SA_CONNECTION_STRING}
  sa-name: standinevents
  consumer-group: $Default
  consumer:
    ##permette di abilitare/disabilitare il consumer
    enabled: 'true'
  write:
    ##permettono di abilitare/disabilitare la scrittura di stand-in sui vari database
    pagopa-postgres: 'true'
    nexi-postgres: 'false'
    nexi-oracle: 'true'

api-config-cache:
  rx-connection-string: ${API_CONFIG_CACHE_RX_CONNECTION_STRING}
  rx-name: nodo-dei-pagamenti-cache
  service:
    host: ${API_CONFIG_CACHE_URL}
    subscriptionKey: ${API_CONFIG_CACHE_SUBSCRIPTION_KEY}
    ##permette di abilitare/disabilitare la chiamata al servizio tramite API
    enabled: 'true'
  sa-connection-string: ${API_CONFIG_CACHE_SA_CONNECTION_STRING}
  sa-name: cacheevents
  consumer-group: $Default
  consumer:
    ##permette di abilitare/disabilitare il consumer
    enabled: 'true'
  write:
    ##permettono di abilitare/disabilitare la scrittura di cache sui vari database
    pagopa-postgres: 'true'
    nexi-postgres: 'false'
    nexi-oracle: 'true'

logging:
  level:
    it:
      gov:
        pagopa: ${APP_LOGGING_LEVEL:INFO}
    root: ${DEFAULT_LOGGING_LEVEL:INFO}