apiVersion: v2
name: pagopa-node-cfg-sync
description: Microservice that sync api-config-cache and standin configuration
type: application
version: 0.78.0
appVersion: 0.0.5-1-NOD-822_viste
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
